id: P9A84E2E9
initial_creation_type: input
source_metadata:
  title: Shechen Gyaltsab Gyurme Pema Namgyal
  language: de
  description: 'Texts by and about Shechen Gyatsab Gyurme Pema Namgyal (zhe chen rgyal
    tshab ''gyur med padma rnam rgyal, 1871–1926):'
  volume:
    882c973fca6e485191270a5820077ac6:
      title: Advice for Gelong Jampa Dargye
      parent: Advice
    b1315330faae4c608ffe4f4e6a3e5523:
      title: A Prayer of Aspiration
      parent: Aspiration Prayers
    fe735eff1cdd4ff9964a3dee788995e5:
      title: Lamp Aspiration Prayer
      parent: Aspiration Prayers
    d8ffc02617cd494f99cb7a00f8b050dc:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    645a187a7b764001a0f1d0f5acdfd6e1:
      title: Brief Offering Prayer to Gesar
      parent: Dharma Protectors
    b3ae1e515282436ba0be0ed479ac731f:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Dharma Protectors
    ed7b8d19cf654f0c82f772ad5381caed:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    5d4735a9a41f4103bb265f0020b27ace:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    ea352681061949359f1e823b5c4201b8:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    b75bf8fcdc5244ed8686e70b058ea381:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    a6a6b32193054c5892482cefba686187:
      title: A Prayer To Padmasambhava
      parent: Prayers
    58851aa152f94ee8908c72672e168abf:
      title: A Prayer to Amitāyus
      parent: Prayers
    aa338b8002a84db7914cd2eed555b0b5:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    96baef38279f4f52b62b8f9955d48e5d:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Prayers
    045016394fdd414eb83808e8f5ac2674:
      title: A Concise Feast Prayer
      parent: Tsok
created_at: '2022-03-01T01:34:05.451847'
last_modified_at: '2022-03-01T01:34:05.451850'
